/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DTO.DiemRequestDTO;
import Models.Diem;
import Models.DiemId;
import DTO.DiemResponseDTO;
import DTO.SinhVienDTO;
import Models.HocKy;
import Models.Monhoc;
import Models.SinhVien;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.reflect.Type;
import javax.swing.JComboBox;
import main.qlsinhvien.AdminMainMenu;

/**
 *
 * @author LNV
 */
public class NhapDiemView extends javax.swing.JPanel {

    private java.util.HashMap<String, String> monMap = new java.util.HashMap<>(); // key = tên sinhvien, value = mã sv
    private java.util.HashMap<String, String> monMapReverse = new java.util.HashMap<>();  // key = mã sv, value = tên sv

    private java.util.HashMap<String, String> hkMap = new java.util.HashMap<>(); // key = tên hk, value = mã hk
    private java.util.HashMap<String, String> hkMapReverse = new java.util.HashMap<>();  // key = mã hk, value = tên hk

    /**
     * Creates new form NhapDiemView
     */
    public NhapDiemView() {
        initComponents();
        loadhocky();

        cbxmonhoc.addActionListener(e -> loadSinhVienChuaCoDiem());
        cbxhocky.addActionListener(e -> loadmonhoc());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnsavediem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cbxhocky = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxmonhoc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sv", "Họ tên", "Môn học", "Điểm"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnsavediem.setText("Lưu điểm");
        btnsavediem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavediemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nhập điểm cho sinh viên");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbxhocky.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Chọn học kỳ---" }));

        jLabel3.setText("Chọn học kỳ:");

        jLabel4.setText("Chọn môn học:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxhocky, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxmonhoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxhocky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnsavediem))
                    .addComponent(jLabel1))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsavediem)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 private void loadhocky() {
        try {
            URL url = new URL("http://localhost:8080/api/hocky");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");

            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream(), StandardCharsets.UTF_8));
            StringBuilder response = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            Gson gson = new Gson();
            HocKy[] list = gson.fromJson(response.toString(), HocKy[].class);

            cbxhocky.removeAllItems();
            cbxhocky.addItem("---Chọn học kỳ---");

            for (HocKy hk : list) {
                cbxhocky.addItem(hk.getTenhk());
                hkMap.put(hk.getTenhk(), hk.getMahk());
                hkMapReverse.put(hk.getMahk(), hk.getTenhk());
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi nạp dữ liệu học kỳ!");
        }
    }

    private void loadmonhoc() {
        try {
            String selectedText = cbxhocky.getSelectedItem().toString();
            String selectedhk = hkMap.get(selectedText);
            URL url = new URL("http://localhost:8080/api/mon/theohocky/" + URLEncoder.encode(selectedhk, "UTF-8"));
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");

            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream(), StandardCharsets.UTF_8));
            StringBuilder response = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            Gson gson = new Gson();
            Monhoc[] list = gson.fromJson(response.toString(), Monhoc[].class);

            cbxmonhoc.removeAllItems();
            cbxmonhoc.addItem("---Chọn môn học---");
            for (Monhoc mh : list) {
                cbxmonhoc.addItem(mh.getTenmon());
                monMap.put(mh.getTenmon(), mh.getMamon()); // Tạo map để tra ngược khi cần mã
                monMapReverse.put(mh.getMamon(), mh.getTenmon()); // Ngược lại
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi nạp dữ liệu môn học!");
        }
    }
    private void btnsavediemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavediemActionPerformed
        if (jTable1.isEditing()) {
            jTable1.getCellEditor().stopCellEditing();
        }
        int monIndex = cbxmonhoc.getSelectedIndex();
        int hkIndex = cbxhocky.getSelectedIndex();
        if (monIndex <= 0 || hkIndex <= 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn môn học và học kỳ.");
            return;
        }

        String mamon = monMap.get(cbxmonhoc.getSelectedItem().toString());
        int mahk = Integer.parseInt(hkMap.get(cbxhocky.getSelectedItem().toString()));

        boolean hasError = false;
        int countSaved = 0;
        Gson gson = new Gson();

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String masv = jTable1.getValueAt(i, 0).toString();
            Object diemObj = jTable1.getValueAt(i, 2);

            if (diemObj == null || diemObj.toString().trim().isEmpty()) {
                continue;
            }

            try {
                double diem = Double.parseDouble(diemObj.toString());
                if (diem < 0 || diem > 10) {
                    JOptionPane.showMessageDialog(this, "Điểm không hợp lệ ở dòng " + (i + 1) + ". Vui lòng nhập từ 0 đến 10.");
                    hasError = true;
                    continue;
                }

                DiemRequestDTO dto = new DiemRequestDTO(masv, mamon, mahk, diem);

                HttpURLConnection conn = (HttpURLConnection) new URL("http://localhost:8080/api/diem").openConnection();
                conn.setRequestMethod("POST");
                conn.setRequestProperty("Content-Type", "application/json");
                conn.setDoOutput(true);

                try (OutputStream os = conn.getOutputStream()) {
                    os.write(gson.toJson(dto).getBytes("UTF-8"));
                }

                if (conn.getResponseCode() == HttpURLConnection.HTTP_OK) {
                    countSaved++;
                } else {
                    hasError = true;
                    String error = new BufferedReader(new InputStreamReader(conn.getErrorStream(), "UTF-8"))
                            .lines().reduce("", (a, b) -> a + b);
                    JOptionPane.showMessageDialog(this, "Lỗi lưu SV " + masv + ": " + error);
                }

                conn.disconnect();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Điểm không hợp lệ ở dòng " + (i + 1));
                hasError = true;
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Lỗi lưu điểm SV " + masv);
                hasError = true;
            }
        }

        if (!hasError && countSaved > 0) {

            JOptionPane.showMessageDialog(this, "Đã lưu " + countSaved + " điểm thành công!");
            loadSinhVienChuaCoDiem();
        }
    }//GEN-LAST:event_btnsavediemActionPerformed

    private void loadSinhVienChuaCoDiem() {
        int monIndex = cbxmonhoc.getSelectedIndex();
        int hkIndex = cbxhocky.getSelectedIndex();

        if (monIndex <= 0 || hkIndex <= 0) {
            System.out.println("Vui lòng chọn môn học và học kỳ hợp lệ.");
            return;
        }

        String mamon = monMap.get(cbxmonhoc.getSelectedItem().toString());
        String mahk = hkMap.get(cbxhocky.getSelectedItem().toString());

        try {
            String apiUrl = "http://localhost:8080/api/diem/chuacodiem?mamon="
                    + URLEncoder.encode(mamon, "UTF-8")
                    + "&mahk=" + URLEncoder.encode(mahk, "UTF-8");

            URL url = new URL(apiUrl);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Accept", "application/json");

            if (conn.getResponseCode() != 200) {
                throw new RuntimeException("Lỗi HTTP: " + conn.getResponseCode());
            }

            BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream(), "UTF-8"));
            StringBuilder response = new StringBuilder();
            String line;
            while ((line = br.readLine()) != null) {
                response.append(line);
            }
            conn.disconnect();

            Gson gson = new Gson();
            SinhVienDTO[] danhSach = gson.fromJson(response.toString(), SinhVienDTO[].class);

            // Hiển thị dữ liệu lên JTable
            DefaultTableModel model = new DefaultTableModel(new Object[]{"Mã SV", "Họ tên", "Điểm"}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    // Chỉ cho phép chỉnh sửa cột "Điểm"
                    return column == 2;
                }
            };

            for (SinhVienDTO sv : danhSach) {
                model.addRow(new Object[]{sv.getMasv(), sv.getHoten()});
            }

            jTable1.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lỗi khi tải danh sách sinh viên chưa có điểm!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsavediem;
    private javax.swing.JComboBox<String> cbxhocky;
    private javax.swing.JComboBox<String> cbxmonhoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
