/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.qlsinhvien;

import Controllers.LoginController;
import Models.Diem;
import Views.DangKyView;

import Views.HocPhiView;
import Views.HocKyView;
import Views.Home;
import Views.Ketquahoctap;
import Views.Login;
import Views.LopView;
import Views.MonView;
import Views.NhapDiemView;
import Views.TaikhoanView;
import Views.ThongKeVIew;
import Views.XemDiemView;
import Views.sinhvien;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author LNV
 */
public class AdminMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AdminMainMenu() {
        initComponents();
        this.setResizable(false);
        Home view = new Home(this);
        setContentPanel(view);
    }

    public void setContentPanel(JPanel panel) {
        contentpanel.removeAll();
        contentpanel.setLayout(new BorderLayout());

        JScrollPane scrollPane = new JScrollPane(panel);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(8, Integer.MAX_VALUE));
        scrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(Integer.MAX_VALUE, 8));
        scrollPane.setBorder(null);
        contentpanel.add(scrollPane, BorderLayout.CENTER);
        contentpanel.revalidate();
        contentpanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        FooterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NavigationPanel = new javax.swing.JPanel();
        btnsv = new javax.swing.JButton();
        btnmon = new javax.swing.JButton();
        btnlop = new javax.swing.JButton();
        btnhocky = new javax.swing.JButton();
        btndkmon = new javax.swing.JButton();
        btnnhapdiem = new javax.swing.JButton();
        btnxemdiem = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnhocphi = new javax.swing.JButton();
        btntaikhoan = new javax.swing.JButton();
        contentpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(0, 123, 255));
        header.setPreferredSize(new java.awt.Dimension(745, 57));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ SINH VIÊN");

        btnhome.setBackground(new java.awt.Color(0, 123, 255));
        btnhome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setText("Trang chủ");
        btnhome.setBorder(null);
        btnhome.setContentAreaFilled(false);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(0, 123, 255));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Đăng xuất");
        btnlogout.setBorder(null);
        btnlogout.setContentAreaFilled(false);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(btnhome)
                .addGap(18, 18, 18)
                .addComponent(btnlogout)
                .addGap(16, 16, 16))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhome)
                    .addComponent(btnlogout)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        FooterPanel.setBackground(new java.awt.Color(0, 123, 255));
        FooterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        FooterPanel.setPreferredSize(new java.awt.Dimension(745, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© 2025 Student Management System. All rights reserved.");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(184, 184, 184))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(FooterPanel, java.awt.BorderLayout.PAGE_END);

        NavigationPanel.setBackground(new java.awt.Color(36, 61, 85));
        NavigationPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(10, 10, 20, 10)));
        NavigationPanel.setPreferredSize(new java.awt.Dimension(130, 271));
        NavigationPanel.setLayout(new java.awt.GridLayout(12, 1, 5, 5));

        btnsv.setBackground(new java.awt.Color(52, 58, 64));
        btnsv.setForeground(new java.awt.Color(255, 255, 255));
        btnsv.setText("Quản lý SV");
        btnsv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btnsv.setBorderPainted(false);
        btnsv.setContentAreaFilled(false);
        btnsv.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsvActionPerformed(evt);
            }
        });
        NavigationPanel.add(btnsv);

        btnmon.setBackground(new java.awt.Color(52, 58, 64));
        btnmon.setForeground(new java.awt.Color(255, 255, 255));
        btnmon.setText("Quản lý môn");
        btnmon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btnmon.setContentAreaFilled(false);
        btnmon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmonActionPerformed(evt);
            }
        });
        NavigationPanel.add(btnmon);

        btnlop.setBackground(new java.awt.Color(52, 58, 64));
        btnlop.setForeground(new java.awt.Color(255, 255, 255));
        btnlop.setText("Quản lý lớp");
        btnlop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btnlop.setContentAreaFilled(false);
        btnlop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlopActionPerformed(evt);
            }
        });
        NavigationPanel.add(btnlop);

        btnhocky.setBackground(new java.awt.Color(52, 58, 64));
        btnhocky.setForeground(new java.awt.Color(255, 255, 255));
        btnhocky.setText("Học kỳ");
        btnhocky.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btnhocky.setContentAreaFilled(false);
        btnhocky.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnhocky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhockyActionPerformed(evt);
            }
        });
        NavigationPanel.add(btnhocky);

        btndkmon.setBackground(new java.awt.Color(52, 58, 64));
        btndkmon.setForeground(new java.awt.Color(255, 255, 255));
        btndkmon.setText("Đăng kí môn");
        btndkmon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btndkmon.setContentAreaFilled(false);
        btndkmon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndkmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndkmonActionPerformed(evt);
            }
        });
        NavigationPanel.add(btndkmon);

        btnnhapdiem.setBackground(new java.awt.Color(52, 58, 64));
        btnnhapdiem.setForeground(new java.awt.Color(255, 255, 255));
        btnnhapdiem.setText("Nhập điểm");
        btnnhapdiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btnnhapdiem.setContentAreaFilled(false);
        btnnhapdiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnnhapdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhapdiemActionPerformed(evt);
            }
        });
        NavigationPanel.add(btnnhapdiem);

        btnxemdiem.setBackground(new java.awt.Color(52, 58, 64));
        btnxemdiem.setForeground(new java.awt.Color(255, 255, 255));
        btnxemdiem.setText("Xem điểm");
        btnxemdiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btnxemdiem.setContentAreaFilled(false);
        btnxemdiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnxemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemdiemActionPerformed(evt);
            }
        });
        NavigationPanel.add(btnxemdiem);

        jButton10.setBackground(new java.awt.Color(52, 58, 64));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Kết quả học");
        jButton10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        jButton10.setContentAreaFilled(false);
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        NavigationPanel.add(jButton10);

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thống kê");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        NavigationPanel.add(jButton1);

        btnhocphi.setBackground(new java.awt.Color(52, 58, 64));
        btnhocphi.setForeground(new java.awt.Color(255, 255, 255));
        btnhocphi.setText("Học phí");
        btnhocphi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btnhocphi.setContentAreaFilled(false);
        btnhocphi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnhocphi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhocphiActionPerformed(evt);
            }
        });
        NavigationPanel.add(btnhocphi);

        btntaikhoan.setBackground(new java.awt.Color(52, 58, 64));
        btntaikhoan.setForeground(new java.awt.Color(255, 255, 255));
        btntaikhoan.setText("Tài khoản");
        btntaikhoan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 18, 1, 1));
        btntaikhoan.setContentAreaFilled(false);
        btntaikhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btntaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaikhoanActionPerformed(evt);
            }
        });
        NavigationPanel.add(btntaikhoan);

        getContentPane().add(NavigationPanel, java.awt.BorderLayout.LINE_START);

        contentpanel.setBackground(new java.awt.Color(255, 255, 255));
        contentpanel.setPreferredSize(new java.awt.Dimension(615, 520));

        javax.swing.GroupLayout contentpanelLayout = new javax.swing.GroupLayout(contentpanel);
        contentpanel.setLayout(contentpanelLayout);
        contentpanelLayout.setHorizontalGroup(
            contentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );
        contentpanelLayout.setVerticalGroup(
            contentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        getContentPane().add(contentpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsvActionPerformed
        sinhvien panel = new sinhvien(); // khởi tạo panel mới
        setContentPanel(panel);
    }//GEN-LAST:event_btnsvActionPerformed

    private void btnmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmonActionPerformed
        MonView panel = new MonView();
        setContentPanel(panel);
    }//GEN-LAST:event_btnmonActionPerformed

    private void btnlopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlopActionPerformed
        LopView view = new LopView();
        setContentPanel(view);
    }//GEN-LAST:event_btnlopActionPerformed

    private void btnhockyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhockyActionPerformed
        HocKyView view = new HocKyView();
        setContentPanel(view);
    }//GEN-LAST:event_btnhockyActionPerformed

    private void btndkmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndkmonActionPerformed
        DangKyView panel = new DangKyView(this); // khởi tạo panel mới
        setContentPanel(panel);
    }//GEN-LAST:event_btndkmonActionPerformed

    private void btnnhapdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhapdiemActionPerformed
        NhapDiemView view = new NhapDiemView();
        setContentPanel(view);
    }//GEN-LAST:event_btnnhapdiemActionPerformed

    private void btnxemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemdiemActionPerformed
        XemDiemView view = new XemDiemView();
        setContentPanel(view);
    }//GEN-LAST:event_btnxemdiemActionPerformed

    private void btnhocphiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhocphiActionPerformed
        HocPhiView view = new HocPhiView();
        setContentPanel(view);
    }//GEN-LAST:event_btnhocphiActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        Home view = new Home(this);
        setContentPanel(view);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btntaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaikhoanActionPerformed
        TaikhoanView view = new TaikhoanView();
        setContentPanel(view);
    }//GEN-LAST:event_btntaikhoanActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (result == JOptionPane.YES_OPTION) {
            // Mở lại form Login
            Login loginForm = new Login();
            new LoginController(loginForm);
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);

            // Đóng form hiện tại
            this.dispose(); // hoặc ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Ketquahoctap panel = new Ketquahoctap();
        setContentPanel(panel);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ThongKeVIew panel = new ThongKeVIew();
        setContentPanel(panel);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminMainMenu view = new AdminMainMenu();
                view.setVisible(true);
                view.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JPanel NavigationPanel;
    private javax.swing.JButton btndkmon;
    private javax.swing.JButton btnhocky;
    private javax.swing.JButton btnhocphi;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnlop;
    private javax.swing.JButton btnmon;
    private javax.swing.JButton btnnhapdiem;
    private javax.swing.JButton btnsv;
    private javax.swing.JButton btntaikhoan;
    private javax.swing.JButton btnxemdiem;
    private javax.swing.JPanel contentpanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
