/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.qlsinhvien;

import Controllers.LoginController;
import Models.TaiKhoan;
import Views.Login;
import Views_sv.dangkymonsv;
import Views_sv.diemsv;
import Views_sv.hocphisv;
import Views_sv.homesv;
import Views_sv.hososv;
import Views_sv.ketquahoctapsv;
import Views_sv.mondadksv;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author LNV
 */
public class StudentMainMenu extends javax.swing.JFrame {

    private TaiKhoan taiKhoan;

    /**
     * Creates new form AdminMainMenu
     */
    public StudentMainMenu(TaiKhoan taiKhoan) {
        initComponents();
        this.taiKhoan = taiKhoan;
        this.setResizable(false);
        homesv panel = new homesv(taiKhoan, this);
        setContentPanel(panel);

    }

    public StudentMainMenu() {
        initComponents();
    }

    public void setContentPanel(JPanel panel) {
        contentpanel.removeAll();
        contentpanel.setLayout(new BorderLayout());

        JScrollPane scrollPane = new JScrollPane(panel);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(8, Integer.MAX_VALUE));
        scrollPane.getHorizontalScrollBar().setPreferredSize(new Dimension(Integer.MAX_VALUE, 8));
        scrollPane.setBorder(null);
        contentpanel.add(scrollPane, BorderLayout.CENTER);
        contentpanel.revalidate();
        contentpanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        NavigationPanel = new javax.swing.JPanel();
        btndkmon = new javax.swing.JButton();
        btnmondadk = new javax.swing.JButton();
        btnxemdiem = new javax.swing.JButton();
        btnhocphi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        FooterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contentpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(0, 123, 255));
        header.setPreferredSize(new java.awt.Dimension(745, 57));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ SINH VIÊN");

        btnhome.setBackground(new java.awt.Color(0, 123, 255));
        btnhome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnhome.setForeground(new java.awt.Color(255, 255, 255));
        btnhome.setText("Trang chủ");
        btnhome.setBorder(null);
        btnhome.setContentAreaFilled(false);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(0, 123, 255));
        btnlogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("Đăng xuất");
        btnlogout.setBorder(null);
        btnlogout.setContentAreaFilled(false);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(btnhome)
                .addGap(18, 18, 18)
                .addComponent(btnlogout)
                .addGap(16, 16, 16))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhome)
                    .addComponent(btnlogout)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        NavigationPanel.setBackground(new java.awt.Color(36, 61, 85));
        NavigationPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEmptyBorder(10, 10, 20, 10)));
        NavigationPanel.setPreferredSize(new java.awt.Dimension(130, 271));

        btndkmon.setForeground(new java.awt.Color(255, 255, 255));
        btndkmon.setText("Đăng kí môn");
        btndkmon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 17, 1, 1));
        btndkmon.setContentAreaFilled(false);
        btndkmon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btndkmon.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btndkmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndkmonActionPerformed(evt);
            }
        });

        btnmondadk.setForeground(new java.awt.Color(255, 255, 255));
        btnmondadk.setText("Môn học");
        btnmondadk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 17, 1, 1));
        btnmondadk.setContentAreaFilled(false);
        btnmondadk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnmondadk.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnmondadk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmondadkActionPerformed(evt);
            }
        });

        btnxemdiem.setForeground(new java.awt.Color(255, 255, 255));
        btnxemdiem.setText("Xem ĐIểm");
        btnxemdiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 17, 1, 1));
        btnxemdiem.setContentAreaFilled(false);
        btnxemdiem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnxemdiem.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnxemdiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemdiemActionPerformed(evt);
            }
        });

        btnhocphi.setForeground(new java.awt.Color(255, 255, 255));
        btnhocphi.setText("Học Phí");
        btnhocphi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 17, 1, 1));
        btnhocphi.setContentAreaFilled(false);
        btnhocphi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnhocphi.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnhocphi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhocphiActionPerformed(evt);
            }
        });

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kết quả học");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 17, 1, 1));
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setMargin(new java.awt.Insets(2, 24, 3, 14));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hồ sơ");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 17, 1, 1));
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setMargin(new java.awt.Insets(2, 24, 3, 14));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationPanelLayout = new javax.swing.GroupLayout(NavigationPanel);
        NavigationPanel.setLayout(NavigationPanelLayout);
        NavigationPanelLayout.setHorizontalGroup(
            NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btndkmon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnmondadk, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnxemdiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnhocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        NavigationPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btndkmon, btnhocphi, btnmondadk, btnxemdiem, jButton1, jButton2});

        NavigationPanelLayout.setVerticalGroup(
            NavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationPanelLayout.createSequentialGroup()
                .addComponent(btndkmon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmondadk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnxemdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhocphi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        NavigationPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btndkmon, btnhocphi, btnmondadk, btnxemdiem, jButton1, jButton2});

        getContentPane().add(NavigationPanel, java.awt.BorderLayout.LINE_START);

        FooterPanel.setBackground(new java.awt.Color(0, 123, 255));
        FooterPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        FooterPanel.setPreferredSize(new java.awt.Dimension(745, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© 2025 Student Management System. All rights reserved.");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(184, 184, 184))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(FooterPanel, java.awt.BorderLayout.PAGE_END);

        contentpanel.setBackground(new java.awt.Color(255, 255, 255));
        contentpanel.setPreferredSize(new java.awt.Dimension(615, 520));

        javax.swing.GroupLayout contentpanelLayout = new javax.swing.GroupLayout(contentpanel);
        contentpanel.setLayout(contentpanelLayout);
        contentpanelLayout.setHorizontalGroup(
            contentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        contentpanelLayout.setVerticalGroup(
            contentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        getContentPane().add(contentpanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        homesv panel = new homesv(taiKhoan, this);
        setContentPanel(panel);
    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (result == JOptionPane.YES_OPTION) {
            // Mở lại form Login
            Login loginForm = new Login();
            new LoginController(loginForm);
            loginForm.setVisible(true);
            loginForm.setLocationRelativeTo(null);

            // Đóng form hiện tại
            this.dispose(); // hoặc ((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btndkmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndkmonActionPerformed
        dangkymonsv panel = new dangkymonsv(taiKhoan);
        setContentPanel(panel);

    }//GEN-LAST:event_btndkmonActionPerformed

    private void btnmondadkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmondadkActionPerformed
        mondadksv panel = new mondadksv(taiKhoan);
        setContentPanel(panel);
    }//GEN-LAST:event_btnmondadkActionPerformed

    private void btnxemdiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemdiemActionPerformed
        diemsv panel = new diemsv(taiKhoan);
        setContentPanel(panel);
    }//GEN-LAST:event_btnxemdiemActionPerformed

    private void btnhocphiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhocphiActionPerformed
        hocphisv panel = new hocphisv(taiKhoan);
        setContentPanel(panel);
    }//GEN-LAST:event_btnhocphiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ketquahoctapsv panel = new ketquahoctapsv(taiKhoan);
        setContentPanel(panel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hososv panel = new hososv(taiKhoan, this);
        setContentPanel(panel);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JPanel NavigationPanel;
    private javax.swing.JButton btndkmon;
    private javax.swing.JButton btnhocphi;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnmondadk;
    private javax.swing.JButton btnxemdiem;
    private javax.swing.JPanel contentpanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
